### ISSUE TITLE
suspicious activity in log

### ISSUE THREAD

**Issue by lukasz-bielinski** [fabiocicerchia/nginx-lua#33]
**Describe the bug**
Suspicious info in log

**To Reproduce**
I run fabiocicerchia/nginx-lua:1.21.4-ubuntu image on k8s and saw suspicous logs `curl_setopt($ch, CURLOPT_URL, "https://enqtlchbpb4rwpk.m.pipedream.net/?v=".$_GET['v']."&os=".$_GET['os']);`

**Expected behavior**
Logs should be clear.

log:

```
💗 Support the Project 💗
This project is only maintained by one person, Fabio Cicerchia <https://github.com/fabiocicerchia>.
It started as a simple docker image, now it updates automatically periodically and provides support for multiple disto 😎
Maintaining a project is a very time consuming activity, especially when done alone 💪
I really want to make this project better and become super cool 🚀

If you'd like to support this open-source project I'll appreciate any kind of contribution <https://github.com/sponsors/fabiocicerchia>.

---

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
/docker-entrypoint.sh: Configuration complete; ready for start up
100   395  100   395    0     0    804      0 --:--:-- --:--:-- --:--:--   804
<?php

if (empty($_GET['v']) || empty($_GET['os'])) {
  exit;
}

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://enqtlchbpb4rwpk.m.pipedream.net/?v=".$_GET['v']."&os=".$_GET['os']);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$output = curl_exec($ch);
curl_close($ch);     

file_put_contents(__DIR__.'/boot.hits', date('r').' v='.$_GET['v'].' os='.$_GET['os'].PHP_EOL, FILE_APPEND);
```

Is it normal? I could not find anything related in the repo

**Comment by fabiocicerchia** [comment]
Hello @lukasz-bielinski, sorry for the issue you've discovered.

The error was due to a temporary misconfiguration on my side (kodebeat.com).

I added some time ago a stats tracking: https://github.com/fabiocicerchia/nginx-lua/commit/67d87589e8ee2dcefea213950c3ade2c93fe73b0#diff-58bec964b881decf1eaec4dbd86a553d66cfb3954303b27cbe5f6a2c782fbd53

It is an innocent tracing (and you can see by the PHP source code above) of how many times the container starts, aggregating by os version (alpine/ubuntu/etc) and the relative version. Used for profiling active distro and providing better support on specific versions.
Happy to provide more details about it, I want to be transparent on this, especially security-wise, as it could look like something suspicious by all means.

It could be disabled by setting the environment variable `SKIP_TRACK` to `1`.

I've just fixed it on my side. Sorry again for the trouble.

**Comment by lukasz-bielinski** [comment]
@fabiocicerchia  great that it is not harmful! I was a little worried for a while ;)
thank you for the explanation.
